intentions/urls.py
from django.contrib import admin
from django.urls import path

from .views import SignUpView
from . import views

app_name = 'intentions'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('home/', views.home, name='home'),
    path('entry/<int:pk>/', views.EntryView.as_view(), name='entry'),
    path('entry_page/', views.entry_page, name='entry_page'),
    path('entries/', views.EntriesView.as_view(), name='entries'),
    path('prompt/<int:pk>', views.PromptView.as_view(), name='prompt'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('intentions.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

intentions/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.


def today_prompt():
    try:
        return Prompt.objects.get(date__date=timezone.localtime(timezone.now()).date())
    except:
        return None


# Prompt Model
class Prompt(models.Model):
    prompt_text = models.CharField(max_length=200)
    date = models.DateTimeField('date')

    def __str__(self):
        return self.prompt_text


# Entries Model
class Entry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    prompt = models.ForeignKey(Prompt, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField('date published')
    mood = models.CharField(max_length=20, default='Okay')
    headspace = models.CharField(max_length=50)
    prompt_response = models.CharField(max_length=2000)
    public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def get_entries(user):
        user_entries = Entry.objects.filter(user=user)
        return user_entries

intentions/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from intentions.models import Entry, Prompt, today_prompt

MOOD_CHOICES = [
    ('Bad', 'Bad'),
    ('Not Good', 'Not Good'),
    ('Okay', 'Okay'),
    ('Pretty Good', 'Pretty Good'),
    ('Great!', 'Great!'),
]


# Custom User Creation Form
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class EntryForm(forms.ModelForm):
    if today_prompt() is not None:
        prompt_text = today_prompt().prompt_text
    else:
        prompt_text = ''

    mood = forms.ChoiceField(
        choices=MOOD_CHOICES, widget=forms.RadioSelect(attrs={'required': 'required'}),
        label='How are you feeling today?')

    headspace = forms.CharField(
        label='In a couple words, what is taking up most of my headspace? (50 Char)',
        max_length=50,
    )

    prompt_response = forms.CharField(
        label=prompt_text + ' (2000 Char)',
        max_length=2000,
        widget=forms.Textarea,
    )

    public = forms.BooleanField(
        label='I would like this prompt response to be public',
        required=False,
        initial=False,
    )

    class Meta:
        model = Entry
        fields = ['mood', 'headspace', 'prompt_response', 'public']

intentions/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone

from intentions.forms import NewUserForm
from django.views import generic
from django.urls import reverse_lazy, reverse

from intentions.models import Prompt, Entry, today_prompt
from .forms import EntryForm
import datetime

# Create your views here.


def home(request):
    return render(request, 'intentions/home.html')


def dashboard(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('intentions:home'))

    count = len(Entry.get_entries(user))
    entries = Entry.get_entries(user).order_by('-date')[:5]
    prompt = today_prompt()
    context = {
        'entries': entries,
        'prompt': prompt,
        'count': count,
    }

    return render(request, 'intentions/dashboard.html', context)


def entry_page(request):
    user = request.user
    prompt = today_prompt()

    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('intentions:home'))
    if request.method == 'POST':
        form = EntryForm(request.POST or None)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.user = user
            new_entry.prompt = prompt
            new_entry.date = timezone.now()
            new_entry.save()
        return HttpResponseRedirect(reverse('intentions:dashboard'))

    form = EntryForm()
    return render(request, 'intentions/entry_page.html', {'form': form})


class EntryView(generic.DetailView):
    model = Entry
    template_name = 'intentions/entry.html'

    def get_queryset(self):
        return Entry.objects.filter(date__lte=timezone.localtime(timezone.now()), user=self.request.user)


class EntriesView(generic.ListView):
    template_name = 'intentions/entries.html'
    context_object_name = 'entries'

    def get_queryset(self):
        entries = Entry.objects.filter(user=self.request.user,).order_by('-date')
        query = self.request.GET.get('title')
        sort = self.request.GET.get('sort')
        filter = self.request.GET.get('filter')
        if query:
            entries = entries.filter(prompt__prompt_text__icontains=query)
        if sort:
            entries = entries.order_by(sort)
        if filter:
            today = datetime.date.today()
            if filter == 'week':
                start_week = today - datetime.timedelta(today.weekday())
                end_week = start_week + datetime.timedelta(days=7)
                entries = entries.filter(date__range=[start_week, end_week])
            if filter == 'month':
                entries = entries.filter(date__month=today.month, date__year=today.year)
            if filter == 'year':
                entries = entries.filter(date__year=today.year)
        return entries

    def get_context_data(self):
        context = super(EntriesView, self).get_context_data()
        query = self.request.GET.get('title')
        sort = self.request.GET.get('sort')
        filter = self.request.GET.get('filter')
        if query:
            context['query'] = query
        else:
            context['query'] = ''
        if sort:
            context['sort'] = sort
        if filter:
            context['filter'] = filter
        return context


class PromptView(generic.DetailView):
    model = Prompt
    template_name = 'intentions/prompt.html'


class SignUpView(generic.CreateView):
    form_class = NewUserForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

intentions/templates/intentions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Base Page{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'intentions/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'intentions/style.css' %}">
    <link rel="shortcut icon" href="{% static 'intentions/images/favicon.jpg' %}">
<body class="d-flex flex-column h-100 bg-light">
    <nav class="navbar navbar-expand-lg navbar-light purple py-1">
        <a class="navbar-brand ml-3 text-white font-weight-normal" href="{% url 'intentions:dashboard' %}">
            <img src="{% static 'intentions/images/intentions-icon.GIF' %}" width="37" height="45" alt="">
                Intentions
        </a>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse my-0 justify-content-end mr-3">
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white" href="{% url 'logout' %}">Log Out</a>
                </div>
            </div>
        {% else %}
            <div class="collapse navbar-collapse my-0 justify-content-end mr-3">
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white" href="{% url 'login' %}">Login</a>
                </div>
            </div>
        {% endif %}
    </nav>
    <main class="">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer mt-auto footer-copyright text-center card-footer purple footer-font-style text-white">
        <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item mx-3">
                <a class="btn btn-social-icon btn-github" href="https://github.com/gabecm" target="_blank">
                    <span class="fa fa-github"></span>
                </a>
            </li>
            <li class="list-inline-item mx-3">
                <a class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com/in/gabriel-mallari/" target="_blank">
                    <span class="fa fa-linkedin"></span>
                </a>
            </li>
            <li class="list-inline-item mx-3">
                <a class="btn btn-social-icon btn-google" href="mailto:gabecmoitproject@gmail.com" target="_blank">
                    <span class="fa fa-google"></span>
                </a>
            </li>
        </ul>
        © Copyright 2021: Intentions
    </footer>

    {# Bootstrap Scripts #}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {# Fontawesome Script #}
    <script src="https://kit.fontawesome.com/8e15fae9ea.js" crossorigin="anonymous"></script>
</body>
</html>

intentions/templates/intentions/dashboard.html
{% extends 'intentions/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dashboard{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            <h2 class="row">Hello, {{user.first_name}}</h2>
            <h2 class="row">You have made <span class="text-purple mx-2"> {{ count }} </span> entries!</h2>
            <div class="row mt-3">
                <div class="col mr-5">
                    <div class="row card">
                        <h6 class="card-header">
                            Recent Entries
                        </h6>
                          <div class="list-group list-group-flush">
                              {% for entry in entries %}
                                  <a href="{% url 'intentions:entry' entry.id %}" class="list-group-item list-group-item-action justify-content-between">
                                      <div class="d-flex w-100 justify-content-between">
                                          {{ entry.prompt }}
                                          <span>{{ entry.date|date:'SHORT_DATE_FORMAT' }}</span>
                                      </div>
                                  </a>
                              {% endfor %}
                          </div>
                    </div>
                    <div class="row">
                        <a type="button" class="mt-3 p-3 col btn btn-purple text-white" href="{% url 'intentions:entries' %}">View Older Entries</a>
                    </div>
                </div>
                <div class="col ml-5">
                    <div class="row card">
                        <h6 class="card-header">
                            Prompt of the Day
                        </h6>
                        {% if prompt %}
                        <div class="card-body">
                            <p class="card-text text-center py-3">{{ prompt.prompt_text }}</p>
                        </div>
                        {% else %}
                         <div class="card-body">
                            <p class="card-text">There is no prompt for today</p>
                        </div>
                        {% endif %}
                    </div>
                    {% if prompt %}
                    <div class="row">
                        <a type="button" class="mt-3 p-3 col btn btn-secondary" href="{% url 'intentions:prompt' prompt.id %}">View Public Responses to this Prompt</a>
                    </div>
                    {% endif %}
                    <div class="row">
                        <a type="button" class="mt-3 p-5 col btn btn-pink text-white btn-lg font-weight-bold" href="{% url 'intentions:entry_page' %}">+ Add a New Entry</a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

intentions/templates/intentions/entries.html
{% extends 'intentions/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Entries Page{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            <h2>{{ user.first_name }}'s Entries</h2>
            <form class="my-3 form-inline" action="{% url 'intentions:entries' %}" method="get">
                {% csrf_token %}
                <div class="form-group mr-2">
                    <input class="form-control mr-sm-2" type="text" name="title" placeholder="Search..." value={{ query }}>
                    <button class="btn btn-purple my-2 my-sm-0 text-white" type="submit">Submit</button>
                </div>
                <div class="form-group border pl-2 mx-2">
                    Sort By:
                    <select class="custom-select ml-2 border-left border-top-0 border-right-0 border-bottom-0" name="sort" onchange="form.submit()">
                        <option value="-date" {% if sort == 'name' or sort == '' %}selected{% endif %}>Most Recent</option>
                        <option value="date" {% if sort == 'date' %}selected{% endif %}>Date Created</option>
                        <option value="prompt__prompt_text" {% if sort == 'prompt__prompt_text' %}selected{% endif %}>Alphabetical</option>
                    </select>
                </div>
                <div class="form-group border pl-2 mx-2">
                    Filter:
                    <select class="custom-select ml-2 border-left border-top-0 border-right-0 border-bottom-0" name="filter" onchange="form.submit()">
                        <option value="all" {% if filter == 'all' or filter == '' %}selected{% endif %}>All Time</option>
                        <option value="week" {% if filter == 'week'%}selected{% endif %}>This Week</option>
                        <option value="month" {% if filter == 'month' %}selected{% endif %}>This Month</option>
                        <option value="year" {% if filter == 'year' %}selected{% endif %}>This Year</option>
                    </select>
                </div>
            </form>
            {% if entries %}
                <div class="list-group">
                    {% for entry in entries %}
                        <a href="{% url 'intentions:entry' entry.id %}" class="list-group-item list-group-item-action justify-content-between d-flex">
                            {{ entry.prompt }}
                            <div>{{ entry.date }}</div>
                        </a>
            {% endfor %}
        </div>
        {% endif %}
        </div>
    {% endblock %}
</body>
</html>

intentions/templates/intentions/entry.html
{% extends 'intentions/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Entry Submission{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="mb-4 border-bottom">
                <h2>Entry of the Day</h2>
                <p>{{ entry.date }}</p>
            </div>

            <div class="my-3">
                <h5>How you were feeling that day:</h5>
                <p class="border p-2">{{ entry.mood }}</p>
            </div>

            <div class="my-3">
                <h5>What was taking up your headspace that day:</h5>
                <p class="border p-2">{{ entry.headspace }}</p>
            </div>

            <div class="my-3 mt-5">
                <h5>Journal Prompt: {{ entry.prompt.prompt_text }}</h5>
                <p class="border p-2">{{ entry.prompt_response }}</p>
            </div>
        </div>
    {% endblock %}
</body>
</html>

intentions/templates/intentions/entry_page.html
{% extends 'intentions/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Daily Entry{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            <h2>Today's Entry</h2>
            <form method="post" class="container-fluid">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-purple text-white px-3" value="Save">
            </form>
        </div>
    {% endblock %}
</body>
</html>

intentions/templates/intentions/home.html
{% extends 'intentions/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            <div class="jumbotron purple">
              <h1 class="display-4 text-white">Welcome to your next journaling app!</h1>
              <p class="lead text-white">Intentions is an online journaling app focused on self-reflection</p>
              <hr class="my-4">
              <p class="text-white">You're able to write daily entries about your mood, respond to thought provoking
                  prompts, and much more!</p>
              <p class="lead text-white">
                  <a class="btn btn-pink btn-lg text-white py-2 px-4" href="{% url 'intentions:signup' %}" role="sign-up">Sign Up</a>
              </p>
            </div>
        </div>
    {% endblock %}
</body>
</html>

intentions/templates/intentions/prompt.html
{% extends 'intentions/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Prompt View{% endblock %}</title>
</head>
<body>
    {% block content %}
        <div class="container my-3">
            <h2>Prompt Responses</h2>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="border-bottom justify-content-between">
                <h4 class="d-inline">{{ prompt.prompt_text }}</h4>
                <span class="d-inline float-right">{{ prompt.date|date:'DATE_FORMAT' }}</span>
            </div>
            <ul class="list_unstyled">
                {% for entry in prompt.entry_set.all %}
                    {% if entry.public %}
                        <li class="media my-3">
                            <img class="mr-3" width="64px" src="{% static 'intentions/images/profile-icon.jpg' %}" alt="Generic placeholder image">
                            <div class="media-body">
                                <h5 class="mt-0 mb-1">
                                    <span class="badge badge-info badge-pill purple">@{{ entry.user.username }}</span>
                                    <small class="badge badge-pill badge-secondary mr-3 pink">{{ entry.date|date:'P'}}</small>
                                </h5>
                                <p>{{ entry.prompt_response }}</p>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endblock %}
</body>
</html>